---
displayName: Java Spring Boot
description: Java stack with OpenJDK 8 and Spring Boot Petclinic demo application
tags: ["Java", "OpenJDK", "Maven", "Spring Boot"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-devfile-registry/images/type-snowdrop.svg?sanitize=true
globalMemoryLimit: 3072Mi
